# Generated by Django 4.2.4 on 2023-09-08 10:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('image', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='classfied',
            new_name='classified',
        ),
    ]
